apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: users
    platform: node
    framework: express
    version: 1.1.0
  name: users
  namespace: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: users
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "3000"
        prometheus.io.path: /metrics
      labels:
        app: users
        platform: node
        framework: express
        version: 1.1.0
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
            - name: NODE_ENV
              value: production
            - name: HTTP_PORT
              value: "3000"
            
            - name: TZ
              value: Europe/Zurich
            
            
            
            
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: db
                  optional: false
          image: 367165238327.dkr.ecr.us-east-1.amazonaws.com/users:1.1.0
          imagePullPolicy: IfNotPresent
          name: users
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
