apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  
  selector:
    app: users
  sessionAffinity: None
  type: NodePort
